spring:
  jmx:
    enabled: true
  liquibase:
    url: jdbc:postgresql://localhost:5433/mydb
    user: postgres
    password: admin
  datasource:
    url: jdbc:postgresql://localhost:5433/mydb
    user: postgres
    password: admin
    
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG