spring:
  liquibase:
    url: jdbc:postgresql://localhost:5433/mydb
    user: postgres
    password: admin
  datasource:
    url: jdbc:postgresql://localhost:5433/mydb
    user: postgres
    password: admin
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/mydb
    username: postgres
    password: admin